#
# Module manifest for module 'Wait-Net'
#
# Generated by: ssg
#
# Generated on: 5/6/2024
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '0.1.1'

# ID used to uniquely identify this module
GUID = '9869277e-cde3-41ce-afe1-2ab401ff3056'

# Author of this module
Author = 'Sedat Kapanoglu'

# Copyright statement for this module
Copyright = '(c) Sedat Kapanoglu. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Provides cmdlets to diagnose Internet connectivity'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()
}

